name: Deploy JavaScript App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Package Application
        run: |
          cd src
          npm run build || echo "Skip if not applicable"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
        run: |
          scp -o StrictHostKeyChecking=no -r ./src ${USERNAME}@${HOST}:/var/www/html
          ssh -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "sudo systemctl restart apache2 || sudo service httpd restart"
