name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired region

      - name: Set up SSH Key
        uses: shimatsu/setup-ssh-key@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Use the EC2 public IP from your GitHub secrets
          username: ${{ secrets.EC2_USER }}  # EC2 username (typically ubuntu, centos, etc.)
          key: ~/.ssh/id_rsa  # Path to your private SSH key (automatically set by setup-ssh-key)
          script: |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt-get install -y nodejs npm

            # Navigate to the deployment directory (adjust path if needed)
            cd /var/www/html  # Change this to the directory where your app should be

            # If necessary, clone the repository
            # git clone https://github.com/your_username/your_repo.git

            # Navigate to the app directory and install dependencies
            # cd your_repo
            npm install

            # Restart the application (if running) or start it
            sudo systemctl restart apache2 || sudo service httpd restart

            # Optionally, run your app (if not served by Apache)
            # npm start
