name: Deploy JavaScript App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload files to EC2
      run: |
        scp -r ./src ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}

    - name: Restart Web Server
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"
